### ISSUE TITLE
`readdir` with `withFileTypes:true` incorrectly includes file name in `path`

### ISSUE THREAD

**Issue by ziacik** [streamich/memfs#1007]
The test here
https://github.com/streamich/memfs/blob/6f4e72e889b578a62110c2e57f79f78e9dbca408/src/__tests__/volume/readdirSync.test.ts#L108

is wrong - node.js actually doesn't include the file name in the path.

So the expectation should be
`{ mode: 33206, name: 'af1', path: '/z' },`

**Comment by zzzzBov** [comment]
I just ran into the same issue.

Looks like the `Dirent.path` property is being set to the full path, rather than the parent path:

https://github.com/streamich/memfs/blob/6f4e72e889b578a62110c2e57f79f78e9dbca408/src/Dirent.ts#L18

_Note how `Link.getPath` includes the name:_

https://github.com/streamich/memfs/blob/6f4e72e889b578a62110c2e57f79f78e9dbca408/src/node.ts#L408-L414

I think it'd make sense to add a `getParentPath()` method to `Link` along the lines of:

```
getParentPath(): string {
  return this.steps.slice(0, -1).join(SEP);
}
```

so that the path assignment in Dirent could be updated to:

```
this.path = link.getParentPath();
```

**Comment by G-Rath** [comment]
PRs are welcome 🙂
