### ISSUE TITLE
Use Memfs with nodegit

### ISSUE THREAD

**Issue by humanely** [streamich/memfs#1057]
Is there a way to use memfs with nodegit?

**Comment by G-Rath** [comment]
Probably not because `nodegit` is a bindings wrapper for `libgit2` so I expect most if not all file system operations are done in C-space rather than JS-space.

I'm going to close this issue since compatibility and usage with `nodegit` specifically isn't a goal of `memfs`, but please feel free to post back any findings you discover about this as it might be useful for others using that library
