### ISSUE TITLE
File descriptor number is out of range

### ISSUE THREAD

**Issue by reinaldoarrosi** [streamich/memfs#274]
The following code throws `RangeError [ERR_INVALID_FD]: "fd" must be a positive integer`

```javascript
var memfs = require('memfs');
var tty = require('tty');

var fd = memfs.openSync('/test', 'w+');
var stream = new tty.WriteStream(fd);
```

This is because the generated file descriptor number exceeds the range of positive integers (32-bit) which causes it to be considered a negative integer. 

I believe the problem is in the Volume class, where the `static fd` variable is defined. It is initialized with 0xffffffff when it should be 0x7fffffff.

**Comment by streamich** [comment]
File descriptors in `memfs` start from `0xffffffff` and are decremented for each new one, it was done in order to avoid conflicting with the real file system file descriptors which start from 3. Maybe it was a bad design decision altogether.

I don't mind lowering it down to `0x7fffffff` or whatever makes sense. I you could make a PR would be great.
