### ISSUE TITLE
TypeScript compiler cannot find name 'BigInt'

### ISSUE THREAD

**Issue by mjfreem1** [streamich/memfs#275]
The BigInt type in the `Stats.d.ts` file causes TypeScript to throw a 2304 (cannot find name) error, so the compilation fails.

TypeScript 2.8.3
memfs 2.14.1

**Comment by streamich** [comment]
1. I think `bigint` was added to TypeScript in 3.2, this project uses Typescript 3.2.2, as of this writing, 
   and it compiles fine.
2. Node.js now supports `bigint` and they are used in the `Stats` class.

I'm not sure what we can do to support `bigint` and old TypeScript users. Any suggestions? Would upgrading to the latest TypeScript be an option?

**Comment by pizzafroide** [comment]
You are right: `BigInt` support was [added to TypeScript 3.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint), and, unfortunately, they say:
> we have no immediate plans to provide downleveling support

However, `BigInt` support was added to `memfs` before it was in `TypeScript`. To make it work, we needed to add `BigInt` definition ourselves (in `bigint.d.ts` file). This file is still there. Maybe it could be copied to `lib` directory at compile time so "old TypeScript" users could import it. @mjfreem1, in the meantime, you can add the following code in some file and import it before importing `memfs`:
```ts
type BigInt = number;
declare const BigInt: typeof Number;
```

**Comment by mjfreem1** [comment]
@streamich @pizzafroide Thanks for your responses. I tried out both suggestions and ended up opting to just upgrade TypeScript. C'est la vie.

**Comment by shlomiassaf** [comment]
@streamich I think there is still an error here.

Your are using the [BigInt](https://github.com/streamich/memfs/blob/master/src/Stats.ts#L6) type, which does not exist in TypeScript, event in 3.2+.

In typescript `BigInt` is the construct (same as ECMAScript) and the type is `bigint`.

This is similar to how other native types are defined (e.g. `String` - `string`)

Now, in your build there are no errors because you still have the [bigint.d.ts](https://github.com/streamich/memfs/blob/master/src/bigint.d.ts) file in the source directory so nothing is wrong... but that file is not exported as part of the package (npm) so it errors on installs.

I can't get it to work...

**Comment by shlomiassaf** [comment]
The workaround for me, without being globally intrusive was to add somewhere in a code that is processed by the typechecker.

```typescript
 declare module 'memfs/lib/Stats.d' {
  type BigInt = number;
}
```
