### ISSUE TITLE
realpath problems on windows

### ISSUE THREAD

**Issue by noamokman** [streamich/memfs#316]
Hey,
I'm having problems with windows and the `realpath` function.
It seems that the `realpath` function always returns the path in a unix format and not windows.

How to reproduce (on windows):
```js
const {resolve} = require('path');
const {vol} = require('memfs');

process.chdir('/');

vol.writeFileSync('package.json', '');

const resolvedPath = resolve('package.json');
const realPath = vol.realpathSync(resolvedPath);

console.log(realPath); // '/package.json'
console.log(resolvedPath); // 'D:\\package.json'
```

What can I do?

**Comment by G-Rath** [comment]
You can [actually manually select](https://nodejs.org/api/path.html#path_windows_vs_posix) what path format the `path` API uses by using the `win32` & `posix` path properties to call path methods:

```
path.posix.resolve
```

I would recommend doing this w/ `memfs`, as it will clear up a lot of problems, and make everything nicely consistent.

Otherwise, there has been talk on "proper" win32 support via #327 - I've not had a proper read, but I might be willing to make a PR if the proposed solution is all that's needed.

Regardless, personally I found switching to using `.posix` resolved *all* my path problems; the Node `fs` API accepts posixs path correctly regardless of OS :)

**Comment by v-dawg** [comment]
The problem I have is that `memfs` cuts out the drive letter and in this example (and in my case), it is not the default drive `C:/` which gets accessed. And Windows automatically thinks that a path without a drive letter should get resolved to `C:/`.
Am I understanding something wrong or is there a way around that?
