### ISSUE TITLE
rename() should work for folders

### ISSUE THREAD

**Issue by KutnerBitsrc** [streamich/memfs#397]
When running .rename() on a folder,
it is expected to rename the folder, and update all file paths in that folder.

But, actually there is no effect. :(

```js
const {vol} = require('memfs')
vol.mkdirSync('/a');
vol.writeFileSync('/a/a.txt', 'hello');
console.log(vol.toJSON()) // {a/a.txt: "hello"}
vol.renameSync('/a/', '/b/')
console.log(vol.toJSON()) // {/a/a.txt: "hello"}
```

**Comment by corwin-of-amber** [comment]
It seems that it changes the directory entries but not the name of the link itself.
```js
> m = require('memfs')
> m.mkdirpSync("/a/b")
> m.writeFileSync("/a/b/c", "d")
> m.renameSync("/a/b", "/a/e")
> m.readdirSync("/a")
[ 'e' ]
> m.readFileSync("/a/e/c")
Uncaught Error: ENOENT: no such file or directory, open '/a/b/c'
    at createError (.../volume.js:131:17)
    at Volume.openLink (.../volume.js:776:19)
...
```

Although directory `/a` contains `e`, the old directory name `b` is still there somehow, and it is picked up by `openLink`.

**Comment by corwin-of-amber** [comment]
Is it possible to make `Link.steps` a property, so that it updates if the parent changes?
https://github.com/streamich/memfs/blob/bb10785965ccc3b7b065e09d70ed8437f4d9dddd/src/node.ts#L257

Otherwise, `steps` has to be recursively updated for children of the moved directory; it is messier, but performance-wise may still be cheaper than recomputing the path on every access.

**Comment by jorenbroekema** [comment]
Hey, is there a workaround for this bug? Currently running into this issue, renaming a directory and following by readFileSync on one of the files in the renamed directory will try to read it from the old directory, and then complain it doesn't exist (which is correct).

I'm glancing over the code seeing if I can help somehow but I'll probably need some directions in order to contribute a fix, as I'm not sure that I understand the nature of the problem.

**Comment by ronakj** [comment]
Just encountered this issue with my tests. Thanks for the fix @jorenbroekema 💯.

**Comment by jorenbroekema** [comment]
You're welcome :)!
