### ISSUE TITLE
Converting from MEMFS to Node FS

### ISSUE THREAD

**Issue by jeff-hykin** [streamich/memfs#538]
This isn't so much an issue as a question (let me know if this is the wrong place for that).

What is the recommended way to convert a MEMFS directory (and all its contents) to a regular file system? Is there a way to do this with the export to JSON, or do I just need to write a recursive readdir->mkdir, readFile->writeFile function myself? Something fast and low level would obviously be ideal, but I can make due with a slow workaround. Permissions are irrelevant to my case, system links would be nice, but I can probably go without.

BTW this repo is awesome!

**Comment by jeff-hykin** [comment]
For anyone else using this with emscripten, there's a NODEFS (node fs) flag you can use that will cause all MEMFS operations to be done to the actual file system. https://emscripten.org/docs/api_reference/Filesystem-API.html#nodefs

I'll leave this question open because there is still the case of performing most operations in memory with MEMFS, and needing to only export a particular folder/file from MEMFS to the actual system file directory.

**Comment by G-Rath** [comment]
I think for now this is best solved in userland since that is where `memfs` already operations so there is no "low level" operation that only the library can do; it could be useful to have a utility function in the library itself so if someone did want to do a PR I would fine landing it, but I don't think this is a must-have.
