### ISSUE TITLE
"Overlaying" memfs?

### ISSUE THREAD

**Issue by kinsi55** [streamich/memfs#551]
It it possible to patch memfs onto nodes original FS methods in combination with unionfs?

The goal:

- ./foo.txt (Exists on original filesystem)
- ./bar.txt (Exists in memfs)

`require("fs").readFileSync("bar.txt")` returns the memfs file, `require("fs").readFileSync("foo.txt")` return the file on the actual disk

When I tried to use fs-monkey and patch using the resulting ufs, as expected, it resulted in an infinite loop / stackoverflow

**Edit**: Did a dirty hack for now where I create my ufs like this `ufs.use({...require("fs")}).use(vol)`. While that works its probably, obviously not the correct usage.

**Comment by G-Rath** [comment]
Yes, that's the idea behind `unionfs` :)

Here's how I monkey patch `fs` in my jest tests:
```
import { createFsFromVolume, vol } from 'memfs';
import { ufs } from 'unionfs';

jest.mock('fs', () => {
  afterEach(() => vol.reset());

  return ufs
    .use(jest.requireActual('fs'))
    .use(createFsFromVolume(vol) as any) as any;
});
```

Personally I'd recommend avoiding the monkey patching if you can avoid it; typically I'd have a file like this:

```
// FileSystem.ts
import * as fs from 'fs';
import { createFsFromVolume, vol } from 'memfs';
import { ufs } from 'unionfs';

export const FileSystem = ufs
    .use(fs)
    .use(createFsFromVolume(vol) as any) as typeof fs;
```

Then in your code you just always use `FileSystem` in place of `fs`.

This of course is not possible if you're using libraries that directly require `fs`, for which you would have to use monkey patching.
There are a number of ways that you can do the patching, all of which are out of scope for this repo as they've got different pros and cons, and monkey patching is itself a very hit-or-miss process.

As an example, it's a good bet the inf. loop issue you had was because you (/fs-monkey) replaced `fs` with ufs, which used `fs`, which was referencing the `fs` that had been monkey patched, and so now it was actually referencing `ufs` which referenced itself.

I can have a look if you want to provide a small example repo, but otherwise I think this is a case of just having to find a good package for monkey patching :)

**Comment by kinsi55** [comment]
I'm using Mocha instead of Jest so I dont really have such tooling, additionally my tested code uses Fs directly - and adding the dist code to accomodate tests - eh I dont know. I guess for now I'll keep using my hack mentioned above (for now (TM)), I just thought that I might've missed something in the docs / other issues. Thank you!

**Comment by G-Rath** [comment]
If you're doing this in a testing framework, I'd recommend using a mocking framework - jest ships with one bulk in, but there's a number of [good ones for mocha](https://github.com/mochajs/mocha/wiki#mocks-stubs--spies) that are very easy to use :)

Replacing `fs` in tests is usually very safe and easy because of the nature of how tests are run (i.e in their own sandbox), so long as you mock the library straight away.

**Comment by kinsi55** [comment]
I will check it out, thanks for the heads up!
