### ISSUE TITLE
[Bug] should fs-monkey be ^1.0.1 instead of 1.0.1?

### ISSUE THREAD

**Issue by wood1986** [streamich/memfs#591]
Currently fs-monkey is "1.0.1". Is it expected? Otherwise, it will have two versions running

**Comment by G-Rath** [comment]
@wood1986 I'm not sure what you mean by "it will have two versions running"?

**Comment by wood1986** [comment]
for example

my package depends on both fs-monkey@1.0.2 and memfs@3.2.0. The node_modules tree will become this

```
|-fs-monkey@1.0.2
|-memfs@3.2.0
   |-fs-monkey@1.0.1
```

unless you can guarantee if fs-monkey introduce a newer version, memfs will introduce a new version at the same time. I mean this will become an issue when fs-monkey releases 1.0.2 regardless of what the renovate bot is doing. Currently fs-monkey is 1.0.1.

**Comment by G-Rath** [comment]
> unless you can guarantee if fs-monkey introduce a newer version, memfs will introduce a new version at the same time

Yes, I can - Renovate will bump the constraint and publish the new version straight away. Because of this it'll also complain if you change the constraints of packages to not be exact.

`fs-monkey` is managed by the same author as this and the other fs libraries, meaning that changes to that library are typically closely tied to this one. It's also a very small library that isn't expected to need changing, so it's very rare for it to have new versions.

*In saying that*, I do agree that it's typically better to have looser constraints - I've not been bothered enough by it (due to the stability mentioned above, and that `fs-monkey` is the only dependency) to put the effort into explore changing it (as I didn't setup the config for renovate, so there might be some discussion), but I might bite that bullet anyway.

I'm going to close your PR and this issue however as if your PR is merged Renovate will open one reverting it, and it shouldn't be a problem as there isn't a later version of `fs-monkey` published :)
