### ISSUE TITLE
readdir sorting implicitly changed on Windows

### ISSUE THREAD

**Issue by ajafff** [streamich/memfs#633]
While working on #632 I noticed that my tests for sorting of `readdir` results didn't work as expected.
Turns out that's because I'm developing on Windows.

The exception for Windows was added in/because of https://github.com/streamich/memfs/issues/37

Regarding case-sensitivity there was a similar discussion in https://github.com/streamich/memfs/issues/533#issuecomment-626401742:

> > the default behavior would be to use system settings
>
>I'm not sure if memfs should "magically" change the way it handles paths; I would prefer it is set explicitly.

Based on that, I'd like to revisit the decision made in #37.

I propose to add an option to `Volume` to enable/disable sorting of `readdir` results. To make this a non-breaking change, the default value for that option could depend on the platform just like it currently does. But it makes it easier to change the behavior without messing with `process.platform`.

**Comment by G-Rath** [comment]
I'm not strongly against adding an option for this, but at the same time feel we don't really need a lot of options for this sort of thing.

As it stands right now it sounds like it's properly emulating what happens on the different platforms, so not sure what the problem is with this?

I also think that this is something you should be accounting for on in your application, as it's not a requirement (afaik) that `readdir` sort the results - as evident by the fact that the native version of `fs.readdir` behaviours differently already

**Comment by G-Rath** [comment]
Closing due to age + inactivity
