### ISSUE TITLE
How to use memfs in jest tests? How to mock fs with mongodb-memory-server?

### ISSUE THREAD

**Issue by alexandrsek** [streamich/memfs#850]
Hello everyone! I need to mock filesystem because I don't want so save files on disk while running tests and want to use temporary or in memory filesystem. Any suggestions how to make it possible?

**Comment by G-Rath** [comment]
You can use [`jest.mock`](https://jestjs.io/docs/mock-functions#mocking-modules) to have `fs` return `memfs` instead of the native `fs` module - you can also combine this with [`unionfs`]() to mock only a slice of the filesystem (this is useful for allowing reading fixture files while having writes be applied to the memory database).

I've used this in a number of my projects - you can see an example of how to set this up [here](https://github.com/G-Rath/audit-app/blob/main/test/setupMockFs.ts). That project also has an example of [how to access the original fs module](https://github.com/G-Rath/audit-app/blob/main/test/src/determineVulnerablePackages.spec.ts#L6-L10)
