### ISSUE TITLE
[Question] Why is `fromJSON` not named `fromObject`?

### ISSUE THREAD

**Issue by ericmorand** [streamich/memfs#975]
Hi community,

I'm just starting to use `memfs` in my test suites and I love it. Still, there is one thing that is confusing to me: why is `vol.fromJSON` named the way it is? The expected argument is not a JSON - which is a _string_ - but a plain JavaScript object:

```ts
import { fs, vol } from 'memfs';

const json = {
  './README.md': '1',
  './src/index.js': '2',
  './node_modules/debug/index.js': '3',
};
vol.fromJSON(json, '/app');
```

Passing a JSON actually doesn't work and is not even accepted by the TypeScript compiler.

I'm asking because I spent a few minutes - not that much - to understand why my code was not working on one of my pure-JavaScript proof of concept before I digged into the source code and discovered that the method was expecting an object and not a JSON.

(By the way, sorry to pollute the issue tracker with that kind of question. I think enabling the Discussions feature for this repository would be quite cool)

EDIT: Actually, even the counterpart method `toJSON` is not returning what its name implies: it returns an object instead of a string.

**Comment by G-Rath** [comment]
It's sort of just a legacy thing that was never important enough to rename - the general idea is that they allow JSON-like interaction which is in particular useful for tests but by requiring/returning an object rather than a JSON string it gives a bit more flexibility.

You're right that the names technically are not the most accurate, but we've not had a lot of problems to make it worth the breaking change of renaming 🙂
